// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  // Supabase: las migraciones necesitan la conexión directa (puerto 5432),
  // no el pooler de PgBouncer que usa la app en runtime (ver src/lib/prisma.ts).
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
